# Generated by Django 4.2.9 on 2024-01-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('in_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=100)),
                ('in_stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
